version: '3.1'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  # This is for email testing
  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - 1080:1080
      - 1025:1025